export const skills = [
  "RESTful APIs",
  "Next JS",
  "Nest JS",
  "Javascript",
  "Typescript",
  "Node JS",
  "Express JS",
  "React JS",
  "Redux",
  "Bootstrap/Material UI/Tailwind CSS",
  "JQuery",
  "Microservices",
  "CI/CD",
  "AWS Services",
  "Git Versioning Control",
  "JIRA",
  "Build Tools",
  "HTML/ CSS",
  "PHP",
  "GITlab/Bitbucket/GitHub",
];
